### ISSUE TITLE
[BUG] prevoted for an invalid block: wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by exodus-justinz** [classic-terra/core#336]
**Describe the bug**
The node throws this error message
```
panic: precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected 44E33FF1736A0144C1B8BC906812802A0E03C2E3971C61CB7A479107DECCE0AF, got 9D3B191ACE94D92906596A1EFC28FE9A2FB1A6E4150E359638E65AD9B81F8CA7

goroutine 85 [running]:
github.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc000e45500, 0xdb0956, 0x0)
	github.com/tendermint/tendermint@v0.34.24/consensus/state.go:1407 +0x179f
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc000e45500, 0xc014056b40, {0xc01404b0e0, 0x28})
	github.com/tendermint/tendermint@v0.34.24/consensus/state.go:2122 +0x188f
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000e45500, 0xc014056b40, {0xc01404b0e0?, 0xc079da0800?})
	github.com/tendermint/tendermint@v0.34.24/consensus/state.go:1948 +0x2c
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000e45500, {{0x2a473c0?, 0xc0137f47f0?}, {0xc01404b0e0?, 0xc014039200?}})
	github.com/tendermint/tendermint@v0.34.24/consensus/state.go:853 +0x44b
github.com/tendermint/tendermint/consensus.(*State).readReplayMessage(0xc000e45500, 0x1ed058a?, {0x0?, 0x0?})
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:81 +0x87f
github.com/tendermint/tendermint/consensus.(*State).catchupReplay(0xc000e45500, 0xdb0956)
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:160 +0x72f
github.com/tendermint/tendermint/consensus.(*State).OnStart(0xc000e45500)
	github.com/tendermint/tendermint@v0.34.24/consensus/state.go:324 +0x19b
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000e45500)
	github.com/tendermint/tendermint@v0.34.24/libs/service/service.go:144 +0x2e9
github.com/tendermint/tendermint/consensus.(*Reactor).SwitchToConsensus(_, {{{0xb, 0x0}, {0xc07aa50c00, 0x7}}, {0xc07aa50c10, 0xa}, 0x1, 0xdb0955, {{0xc07aa6a720, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/consensus/reactor.go:129 +0x197
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc07aaa21c0, 0x0)
	github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:324 +0x115d
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:112 +0x7a
```

**Context & versions**
v2.1.2

**Comment by fmira21** [comment]
+1 here, same error. Tried to apply the latest snapshot, no luck.

**Comment by fmira21** [comment]
My node is Dockerised, will try and write a guidance here if there will be any peculiarities.

**Comment by nghuyenthevinh2000** [comment]
> My node is Dockerised, will try and write a guidance here if there will be any peculiarities.

oh, are you using terra-classic mainnet docker?

**Comment by meteozond** [comment]
Any update on this? 
I've got the same error with 3.0.1 boostrapping from snapshot :(
